### PR TITLE
feat: add typings

### PR DESCRIPTION
**Pull request by rokoroku**
May I add typings?

Since official mobx is written in Typescript, lots of mobx libraries also have built-in typings. (About more information, see [typescript#publishing](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
))

I've happily used this library in my project, and I wrote typing that is compatible with [react-router](https://github.com/ReactTraining/react-router) 3.0 and [history](https://github.com/mjackson/history) 3.0.

If needed, I'll write typings for upcoming v4

### CODE REVIEW

**Comment by alisd23** [comment]
Thanks for this! Looks good. Just have to consider the fact that `Location` and `History` types are duplicated from the `history` and `react-router` libraries, bu hopefully they shouldn't change in their major versions, as it would be a breaking change.
I can't think of any better way of doing it without having `history` and `react-router` as actual dependencies so this way probably makes the most sense. 👍

**Comment by alisd23** [comment]
Also I like the`test-types` idea. Could you make sure that this task fails when the typings are wrong, and then add it to the end of the `test` task so it runs on the CI build too?

**Comment by rokoroku** [comment]
> Looks good. Just have to consider the fact that Location and History types are duplicated from the history and react-router libraries

That's true, but registered typings for ``react-router`` is for 3.0.0 and bundled with ``history``  2.0.0, even it's using 3.0.0. (also, major updates of ``history`` module has lots of breaking changes.)

There is a way to use ``@types`` dependencies provided by [DefinetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), but it doesn't provide a proper way to handle different types per versions (even they are strongly stick with current state of other module, regardless of their version.). And also, we still need to add it as a dependency.

For these reasons, I wrote a ``HistoryLike`` type that can be compatible with any objects that has required properties only for mobx-react-router v3. 

> Also I like thetest-types idea. Could you make sure that this task fails when the typings are wrong, and then add it to the end of the test task so it runs on the CI build too?

Sure, I'll write a code soon.

**Comment by alisd23** [comment]
Cool, I'm happy with this, thanks! 😃

**Pull request merged**
